### ISSUE TITLE
Hive DnR: Combine useAdapter and useOrgHiveAdapters

### ISSUE THREAD

**Issue by daiky00** [refractionPOINT/limacharlie#4]
This ticket is related to the plan to make D&R Rules better.

https://www.notion.so/Ability-to-Manage-Rulesets-6ba215c2b7a0432a98c66731733ebf8c#74a8008d564840b58da4f234d8e5020d

We decided to combine these two stores since they are related to each other. 

Things to consider
1- Adding a 'get' operation to fetch by key minimizing the singular store use.
2- we should be moving the generic hive record type into a types folder/file, either now or later

**Comment by oklex** [comment]
https://www.notion.so/What-is-a-Store-3a9f45d08d5d41869c55bd1b70e760dc
Combining them seems to not be the best way. We don't need to combine them actually, we can keep them separate allow for:
1. an empty model, using an enable flag
2. using mutation keys to track multiple mutations
