### ISSUE TITLE
Default User Login Error

### ISSUE THREAD

**Issue by amittiwari005** [refractionPOINT/limacharlie#53]
I tried to login with default userid/passwd (admin/letmein) and 2ns factor auth. I am getting failed login error message. Kindly assist me in.

**Comment by maximelb** [comment]
Hello, are you referring to your own on-premise deployment or to the free hosted service limacharlie.io?
If this is about your on-premise deployment, confirm you are using the "admin@limacharlie" user and not just "admin". Are you able to do the first login where you change the password and record the 2FA, or is it that first step that's not working?

**Comment by amittiwari005** [comment]
Thanks for your response.Yes I did it for my on-premies deployment and I am loging with admin@limacharlie and letmein. I was successfully logged in at first time after setting 2FA,but don't remember if I have changed the password or made it same as default (letmein). Is there be any way to reset the password?

**Comment by maximelb** [comment]
Ok, here is a temporary solution to reset it to a know value. I will work on a more permanent solution in parallel.

On the backend, start the Cassandra command line: 
```
cqlsh
UPDATE user_info SET salt = '01d960a481360bc7914df965bb87d4bb2b90bcf8aca982a5b06476faef1ff190', salted_password = '2dd0deb5ac09dac649d70a871efb8e171f93653de829666c44e6d04848b66516' WHERE email = 'admin@limacharlie'l
```

This will reset the password to 'letmein' but will not change the 2 factor. Hope that works out for you, let me know if you have any more issues.

**Comment by amittiwari005** [comment]
Thanks for your help
