### ISSUE TITLE
rphcp_debug.exe does not remove hcp_debug.data when uninstall is run

### ISSUE THREAD

**Issue by gaelanadams** [refractionPOINT/limacharlie#56]
In commit 13920a0ecac0b4bd5651dd9cb6e581f4e602213a you add the '-c' for --uninstall-clean that only specifies the C:\Windows\System32\hcp.data file however the debug executable creates C:\Windows\System32\hcp_debug.dat to store enrollment information is also left behind.

**Comment by maximelb** [comment]
Fixed by f53a6255099b71609623915f5b9369886ad040ce.
