### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by 007scorpio** [refractionPOINT/limacharlie#60]
After the change of password i get internal server error.

Note: Am using ubuntu 16.04

Thanks

**Comment by maximelb** [comment]
I will attempt to replicate. Any other details about what you did? Any interesting errors in the /var/log/syslog logs?

**Comment by maximelb** [comment]
I just tried to replicate and was unable. I suggest you try to hop onto our Slack channel at https://limacharlie.herokuapp.com/

That way we can help you troubleshoot the issue in a more timely fashion.
