### ISSUE TITLE
The LimaCharlie backend appears to be offline at the moment

### ISSUE THREAD

**Issue by guy3145** [refractionPOINT/limacharlie#63]
after install i get this error when i try to "login"
how can i fix this?

**Comment by maximelb** [comment]
Hello, unfortunately we have to greatly reduce support for LC Community Edition (what’s open source here on github) as we are shifting priorities towards an Enterprise Edition that is significantly different and much more stable.

That being said, if you have a look at the /var/log/syslog (assuming you are on Ubuntu) as the backend starts and then as you login you should be able to see some error messages that will help you find the issue. Have a look and post here or on the Slack channel if you have any questions about what you’re seeing.

Cheers
Max

**Comment by guy3145** [comment]
Hi Maxim, and thank you for the quick reply. in /var/log/syslog i see this error showing every 5 seconds:
`"Feb 15 07:49:41 ip-172-31-17-183 2018-02-15 07:49:41,569 AdminEndpoint : !!!~~~!!! {'status': {'success': False, 'error': 'exception'}, 'data': {'st': 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/beach/actor.py", line 466, in _opsHandler\n    ret = handler( request )\n  File "<string>", line 32, in wrapped\n  File "<string>", line 138, in cmd_hcp_getAgentStates\n  File "<string>", line 79, in execute\n  File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute\n    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()\n  File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result\n    raise self._final_exception\nNoHostAvailable: (\'Unable to complete the operation against any hosts\', {})\n'}}"`

**Comment by maximelb** [comment]
Ok this is saying Cassandra (the database) is not responding.

This is often, but not always, a symptom of Cassandra running out of memory and crashing. Make sure you have at least 4GB of RAM on the machine you are running the backend on and try to restart Cassandra (sudo service cassandra restart).

**Comment by guy3145** [comment]
thanks, i upgraded the memory to 4gb and now it works!
