### ISSUE TITLE
how to reset admin password

### ISSUE THREAD

**Issue by guy3145** [refractionPOINT/limacharlie#64]
Hi
is it possible to reset the  "admin@limacharlie" user to its default password? we lost our current password and we are unable to login...

Thanks!

**Comment by guy3145** [comment]
when i try to run this command in "cqlsh":
`UPDATE user_info SET salt = '01d960a481360bc7914df965bb87d4bb2b90bcf8aca982a5b06476faef1ff190', salted_password = '2dd0deb5ac09dac649d70a871efb8e171f93653de829666c44e6d04848b66516' WHERE email = 'admin@limacharlie';`
i get an error:
`InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"`

**Comment by maximelb** [comment]
You're almost there. Before doing the UPDATE statement in cqlsh, do `use hcp_analytics;` and then do the update.

**Comment by guy3145** [comment]
i did that now the command excuted succesfully but still unable to login... is it posiible to cancel the 2fa option?

**Comment by maximelb** [comment]
Yes there is: you need to set the mode to off like this:
```sql
use hcp_analytics;
UPDATE configs SET value = 'off' WHERE conf = 'global/2fa_mode';
```

then restart the backend to make sure the setting refreshes right away.

**Comment by guy3145** [comment]
it works! thanks!
