### ISSUE TITLE
HiveDnR: BUG -  Name Issue not able to update/delete DnR Rule

### ISSUE THREAD

**Issue by daiky00** [refractionPOINT/limacharlie#7]
There is an issue with the name of some rules that have special characters and therefore are not been properly formatted.
When you try to make a request to the api with a name that is not properly formatted you run into the issue below in the video

The below links are examples of some of the rule names that are having those issues.

1. https://leinster-gardens.web.app/orgs/8cbe27f4-bfa1-4afb-ba19-138cd51389cd/dr-general/BlackMatter.DarkSide%20Ransomware%20%23001
2. https://leinster-gardens.web.app/orgs/8cbe27f4-bfa1-4afb-ba19-138cd51389cd/dr-general/BlackMatter.DarkSide%20Ransomware%20%23002
3. https://leinster-gardens.web.app/orgs/8cbe27f4-bfa1-4afb-ba19-138cd51389cd/dr-general/BlackMatter.DarkSide%20Ransomware%20%23003

https://user-images.githubusercontent.com/15005162/188240826-5ad20224-e4bb-4341-9292-fdb6327d3e14.mov

**Comment by MrinalN** [comment]
![Image](https://user-images.githubusercontent.com/78000916/189954355-5bb1cec1-6601-4a17-be42-414e4b480afe.png)

**Comment by MrinalN** [comment]
encodeRuleName function

**Comment by oklex** [comment]
https://github.com/refractionPOINT/web-app-frontend/pull/1200
