### ISSUE TITLE
Hive DnR: Rule names with / are having url formatting issues

### ISSUE THREAD

**Issue by daiky00** [refractionPOINT/limacharlie#8]
There is another rule name issue with the special characters in specific the `/`. 

Since we are using the name of a rule to construct the URL. We are running into the issue where the `/` is not been formatted and is been interpret as regular `/` in the URL making the rule appear like it doesnt exist. Below I will attach a video pay attention to the URL.

https://user-images.githubusercontent.com/15005162/188241443-0364edae-3f66-43a7-8f58-bbea96dd509a.mov

**Comment by daiky00** [comment]
There is another rule name issue with the special characters in specific the `/`. 

Since we are using the name of a rule to construct the URL. We are running into the issue where the `/` is not been formatted and is been interpret as regular `/` in the URL making the rule appear like it doesnt exist. Below I will attach a video pay attention to the URL.


https://user-images.githubusercontent.com/15005162/188241443-0364edae-3f66-43a7-8f58-bbea96dd509a.mov

**Comment by MrinalN** [comment]
https://github.com/refractionPOINT/web-app-frontend/commit/4d59f228787df5c8ec5306ea2331f54a1293dc47
