### ISSUE TITLE
Break down the work for Query Console

### ISSUE THREAD

**Issue by rosshaleliuk** [refractionPOINT/limacharlie#9]
Break down the MVP for query console.
Details: https://refractionpoint.slack.com/archives/C01B3RK1S2W/p1673900322756369
Kickoff recording: https://drive.google.com/file/d/1JTL8tuyIR9tV32pX4m5kSiaubEaNXSWp/view?usp=sharing

MVP scope: https://www.notion.so/LCQL-web-UI-V1-919091effa8d49d59043fe9f235c7be8 (to be discussed)

**Comment by oklex** [comment]
I don't think the MVP needs multiple tickets - it's low complexity (relative to what we currently have on the app), just a bit of labor - which would make it just a big-ticket as opposed to a multi-ticket process

**Comment by rosshaleliuk** [comment]
@oklex sounds good - feel free to create one, and get started. I'll close this one
